from fastapi.testclient import TestClient
import pytest
import json
from main import app

client = TestClient(app)



# to test uncomment the function and run pytest -s test_embed_requests.py




# def test_embed_cv():
#     payload = {
#         "id": 105,
#         "technicalSkills": "[{skill=FPGA, level=VHDL}, {skill=Verilog}, {skill=Microcontrollers}, {skill=Arduino}, {skill=ESP32,STM32}, {skill=Data Structures}, {skill=C Java}, {skill=Software Development}, {skill=Java}, {skill=Python}, {skill=C/C++}, {skill=Machine Learning AI Basics}, {skill=Communication and collaboration}, {skill=Problem-Solving Analytical Thinking}]",
#         "foreignLanguages": "[{language=Romanian, proficiency=nativ}, {language=English, proficiency=proficiency Cambridge Certificate}, {language=Italian}]",
#         "education": "[{institution=Universitatea Tehnic? din Cluj-Napoca, degree=Bachelor, field_of_study=Computer Engineering, period={start_date=2022, end_date=2026}, technologies=[]}]",
#         "certifications": "",
#         "projectExperience": "[{title=OpenGL 3D Graphics, description=Developed a C++ and OpenGL application with camera controls, lighting, and texture mapping, technologies=[C++, OpenGL]}, {title=Communication Protocols, description=Implemented SPI, I2C, and Ethernet protocols using VHDL for FPGA systems, technologies=[VHDL, FPGA]}, {title=Volume Hand Control, description=Hand tracking image processing-based project, technologies=[]}]",
#         "workExperience": "[{type=job, title=Roboatelier, company=UTCN, period={date=2024}, description=[Completed a robotics camp focused on Arduino, including an Ultrasonic Radar project], technologies=[Arduino]}, {type=job, title=Cloud Workshop, company=Accenture, period={date=2024}, description=[Learned about AWS Cloud technologies through teamwork-focused exercises], technologies=[AWS]}]",
#         "others": "[{Contact Information=[{Email=muresan.davide2003@yahoo.com}, {Address=Transilvania, Romania}, {LinkedIn=GitHub}], Summary=[Passionate student in Computer Engineering at UTCN, eager to innovate and apply technology to solve real-world problems, I love turning ideas into solutions, exploring new technologies, and constantly pushing my limits to grow, I’m not here to just “do the work.” I’m here to leave my mark and create something cool, Let’s build something awesome!, I am at your service!], Interests and hobbies=[Everything that is related to technology, Hardware, AI/Machine Learning, In terms of sports I’m a swimming enthusiast prefer hiking and exploring the wonders of nature]}]"
#     }
#
#     response = client.post("/embed/cv", json=payload)
#     assert response.status_code == 200
#     assert response.json() == "success"




# def test_embed_jd():
#     payload = { # 13 din mysql
#         "id": 1001,
#         "jobTitle": "Machine Learning Engineer Tech Lead",
#         "companyOverview": "Innovative Solutions Inc. is a leading technology company dedicated to transforming industries through cutting-edge artificial intelligence and machine learning solutions. Our mission is to empower businesses with intelligent systems that drive efficiency, enhance decision-making, and unlock new opportunities. We pride ourselves on fostering a collaborative and inclusive work environment where creativity and innovation thrive.",
#         "keyResponsibilities": "{original_statement=Lead and mentor a team of machine learning engineers, providing technical guidance and career development support., group=[{group=[{task=Lead a team of machine learning engineers}, {task=Mentor a team of machine learning engineers}], group_type=AND}, {task=Provide technical guidance}, {task=Provide career development support}], group_type=AND} {original_statement=Design, develop, and deploy scalable machine learning models and algorithms to solve complex business problems., group=[{task=Design scalable machine learning models and algorithms to solve complex business problems}, {task=Develop scalable machine learning models and algorithms to solve complex business problems}, {task=Deploy scalable machine learning models and algorithms to solve complex business problems}], group_type=AND} {original_statement=Collaborate with cross-functional teams, including data scientists, software engineers, and product managers, to integrate machine learning solutions into products and services., task=Collaborate with cross-functional teams, including data scientists, software engineers, and product managers, to integrate machine learning solutions into products and services} {original_statement=Evaluate and implement state-of-the-art machine learning techniques and tools to enhance model performance and accuracy., group=[{task=Evaluate state-of-the-art machine learning techniques and tools to enhance model performance and accuracy}, {task=Implement state-of-the-art machine learning techniques and tools to enhance model performance and accuracy}], group_type=AND} {original_statement=Oversee the end-to-end lifecycle of machine learning projects, from data collection and preprocessing to model training and deployment., task=Oversee the end-to-end lifecycle of machine learning projects, from data collection and preprocessing to model training and deployment} {original_statement=Ensure best practices in code quality, testing, and documentation are followed within the team., group=[{task=Ensure best practices in code quality are followed within the team}, {task=Ensure best practices in testing are followed within the team}, {task=Ensure best practices in documentation are followed within the team}], group_type=AND} {original_statement=Stay updated with the latest advancements in machine learning and AI technologies, and drive innovation within the team., group=[{task=Stay updated with the latest advancements in machine learning and AI technologies}, {task=Drive innovation within the team}], group_type=AND}",
#         "requiredQualifications": "{original_statement=Bachelor’s or Master’s degree in Computer Science, Engineering, Mathematics, or a related field., group=[{group=[{requirement=Bachelor’s degree in Computer Science, Engineering, Mathematics, or a related field}, {requirement=Master’s degree in Computer Science, Engineering, Mathematics, or a related field}], group_type=OR}], group_type=AND} {original_statement=Minimum of 5 years of experience in machine learning, with at least 2 years in a leadership or tech lead role., group=[{requirement=Minimum of 5 years of experience in machine learning}, {requirement=At least 2 years in a leadership role}, {requirement=At least 2 years in a tech lead role}], group_type=AND} {original_statement=Strong proficiency in Python and experience with machine learning frameworks such as TensorFlow, PyTorch, or Scikit-learn., group=[{requirement=Strong proficiency in Python}, {requirement=Experience with machine learning frameworks such as TensorFlow, PyTorch, or Scikit-learn}], group_type=AND} {original_statement=Proven track record of deploying machine learning models in production environments., requirement=Proven track record of deploying machine learning models in production environments} {original_statement=Excellent problem-solving skills and the ability to work independently and collaboratively in a fast-paced environment., group=[{requirement=Excellent problem-solving skills}, {requirement=The ability to work independently in a fast-paced environment}, {requirement=The ability to work collaboratively in a fast-paced environment}], group_type=AND} {original_statement=Strong communication skills, with the ability to convey complex technical concepts to non-technical stakeholders., requirement=Strong communication skills, with the ability to convey complex technical concepts to non-technical stakeholders}",
#         "preferredSkills": "{original_statement=Experience with cloud platforms such as AWS, Google Cloud, or Azure., group=[{group=[{skill=Experience with cloud platforms such as AWS}, {skill=Experience with cloud platforms such as Google Cloud}, {skill=Experience with cloud platforms such as Azure}], group_type=OR}], group_type=AND} {original_statement=Familiarity with big data technologies like Hadoop, Spark, or Kafka., group=[{group=[{skill=Familiarity with big data technologies like Hadoop}, {skill=Familiarity with big data technologies like Spark}, {skill=Familiarity with big data technologies like Kafka}], group_type=OR}], group_type=AND} {original_statement=Knowledge of deep learning architectures and natural language processing., group=[{skill=Knowledge of deep learning architectures}, {skill=Knowledge of natural language processing}], group_type=AND} {original_statement=Experience with version control systems, such as Git, and CI/CD pipelines., group=[{skill=Experience with version control systems, such as Git}, {skill=Experience with CI/CD pipelines}], group_type=AND} {original_statement=Strong understanding of data structures, algorithms, and software design principles., group=[{skill=Strong understanding of data structures}, {skill=Strong understanding of algorithms}, {skill=Strong understanding of software design principles}], group_type=AND}",
#         "message": "AI and Machine Learning Solutions industry"
#     }
#
#     response = client.post("/embed/jd", json=payload)
#     assert response.status_code == 200
#     assert response.json() == "success"

#
#
# def test_match_jd():
#     job_skills = {"Python": 30, "TensorFlow": 20, "NPL": 20, "Teamwork": 30}
#     jd_payload = {
#         "id": 1001,
#         "jobTitle": "Machine Learning Engineer Tech Lead",
#         "companyOverview": "Innovative Solutions Inc. is a leading technology company dedicated to transforming industries through cutting-edge artificial intelligence and machine learning solutions. Our mission is to empower businesses with intelligent systems that drive efficiency, enhance decision-making, and unlock new opportunities. We pride ourselves on fostering a collaborative and inclusive work environment where creativity and innovation thrive.",
#         "keyResponsibilities": "{original_statement=Lead and mentor a team of machine learning engineers, providing technical guidance and career development support., group=[{group=[{task=Lead a team of machine learning engineers}, {task=Mentor a team of machine learning engineers}], group_type=AND}, {task=Provide technical guidance}, {task=Provide career development support}], group_type=AND} {original_statement=Design, develop, and deploy scalable machine learning models and algorithms to solve complex business problems., group=[{task=Design scalable machine learning models and algorithms to solve complex business problems}, {task=Develop scalable machine learning models and algorithms to solve complex business problems}, {task=Deploy scalable machine learning models and algorithms to solve complex business problems}], group_type=AND} {original_statement=Collaborate with cross-functional teams, including data scientists, software engineers, and product managers, to integrate machine learning solutions into products and services., task=Collaborate with cross-functional teams, including data scientists, software engineers, and product managers, to integrate machine learning solutions into products and services} {original_statement=Evaluate and implement state-of-the-art machine learning techniques and tools to enhance model performance and accuracy., group=[{task=Evaluate state-of-the-art machine learning techniques and tools to enhance model performance and accuracy}, {task=Implement state-of-the-art machine learning techniques and tools to enhance model performance and accuracy}], group_type=AND} {original_statement=Oversee the end-to-end lifecycle of machine learning projects, from data collection and preprocessing to model training and deployment., task=Oversee the end-to-end lifecycle of machine learning projects, from data collection and preprocessing to model training and deployment} {original_statement=Ensure best practices in code quality, testing, and documentation are followed within the team., group=[{task=Ensure best practices in code quality are followed within the team}, {task=Ensure best practices in testing are followed within the team}, {task=Ensure best practices in documentation are followed within the team}], group_type=AND} {original_statement=Stay updated with the latest advancements in machine learning and AI technologies, and drive innovation within the team., group=[{task=Stay updated with the latest advancements in machine learning and AI technologies}, {task=Drive innovation within the team}], group_type=AND}",
#         "requiredQualifications": "{original_statement=Bachelor’s or Master’s degree in Computer Science, Engineering, Mathematics, or a related field., group=[{group=[{requirement=Bachelor’s degree in Computer Science, Engineering, Mathematics, or a related field}, {requirement=Master’s degree in Computer Science, Engineering, Mathematics, or a related field}], group_type=OR}], group_type=AND} {original_statement=Minimum of 5 years of experience in machine learning, with at least 2 years in a leadership or tech lead role., group=[{requirement=Minimum of 5 years of experience in machine learning}, {requirement=At least 2 years in a leadership role}, {requirement=At least 2 years in a tech lead role}], group_type=AND} {original_statement=Strong proficiency in Python and experience with machine learning frameworks such as TensorFlow, PyTorch, or Scikit-learn., group=[{requirement=Strong proficiency in Python}, {requirement=Experience with machine learning frameworks such as TensorFlow, PyTorch, or Scikit-learn}], group_type=AND} {original_statement=Proven track record of deploying machine learning models in production environments., requirement=Proven track record of deploying machine learning models in production environments} {original_statement=Excellent problem-solving skills and the ability to work independently and collaboratively in a fast-paced environment., group=[{requirement=Excellent problem-solving skills}, {requirement=The ability to work independently in a fast-paced environment}, {requirement=The ability to work collaboratively in a fast-paced environment}], group_type=AND} {original_statement=Strong communication skills, with the ability to convey complex technical concepts to non-technical stakeholders., requirement=Strong communication skills, with the ability to convey complex technical concepts to non-technical stakeholders}",
#         "preferredSkills": "{original_statement=Experience with cloud platforms such as AWS, Google Cloud, or Azure., group=[{group=[{skill=Experience with cloud platforms such as AWS}, {skill=Experience with cloud platforms such as Google Cloud}, {skill=Experience with cloud platforms such as Azure}], group_type=OR}], group_type=AND} {original_statement=Familiarity with big data technologies like Hadoop, Spark, or Kafka., group=[{group=[{skill=Familiarity with big data technologies like Hadoop}, {skill=Familiarity with big data technologies like Spark}, {skill=Familiarity with big data technologies like Kafka}], group_type=OR}], group_type=AND} {original_statement=Knowledge of deep learning architectures and natural language processing., group=[{skill=Knowledge of deep learning architectures}, {skill=Knowledge of natural language processing}], group_type=AND} {original_statement=Experience with version control systems, such as Git, and CI/CD pipelines., group=[{skill=Experience with version control systems, such as Git}, {skill=Experience with CI/CD pipelines}], group_type=AND} {original_statement=Strong understanding of data structures, algorithms, and software design principles., group=[{skill=Strong understanding of data structures}, {skill=Strong understanding of algorithms}, {skill=Strong understanding of software design principles}], group_type=AND}",
#         "message": "AI and Machine Learning Solutions industry"
#     }
#     request_payload = {
#         "jd": jd_payload,
#         "job_skills": job_skills
#     }
#
#     response = client.post("/match/jd", json=request_payload)
#
#     # Afisarea răspunsului pentru vizualizare
#     print(response.json())
#
#     assert response.status_code == 200
#     assert isinstance(response.json(), list)
#     assert len(response.json()) > 0
#     assert "score" in response.json()[0]
#     assert "explanation" in response.json()[0]
#     assert "id" in response.json()[0]
#
#
# def test_match_cv():
#     jd_payload_1 = {
#         "id": 1001,
#         "jobTitle": "Machine Learning Engineer Tech Lead",
#         "companyOverview": "Innovative Solutions Inc. is a leading technology company dedicated to transforming industries through cutting-edge artificial intelligence and machine learning solutions. Our mission is to empower businesses with intelligent systems that drive efficiency, enhance decision-making, and unlock new opportunities. We pride ourselves on fostering a collaborative and inclusive work environment where creativity and innovation thrive.",
#         "keyResponsibilities": "{original_statement=Lead and mentor a team of machine learning engineers, providing technical guidance and career development support., group=[{group=[{task=Lead a team of machine learning engineers}, {task=Mentor a team of machine learning engineers}], group_type=AND}, {task=Provide technical guidance}, {task=Provide career development support}], group_type=AND} {original_statement=Design, develop, and deploy scalable machine learning models and algorithms to solve complex business problems., group=[{task=Design scalable machine learning models and algorithms to solve complex business problems}, {task=Develop scalable machine learning models and algorithms to solve complex business problems}, {task=Deploy scalable machine learning models and algorithms to solve complex business problems}], group_type=AND} {original_statement=Collaborate with cross-functional teams, including data scientists, software engineers, and product managers, to integrate machine learning solutions into products and services., task=Collaborate with cross-functional teams, including data scientists, software engineers, and product managers, to integrate machine learning solutions into products and services} {original_statement=Evaluate and implement state-of-the-art machine learning techniques and tools to enhance model performance and accuracy., group=[{task=Evaluate state-of-the-art machine learning techniques and tools to enhance model performance and accuracy}, {task=Implement state-of-the-art machine learning techniques and tools to enhance model performance and accuracy}], group_type=AND} {original_statement=Oversee the end-to-end lifecycle of machine learning projects, from data collection and preprocessing to model training and deployment., task=Oversee the end-to-end lifecycle of machine learning projects, from data collection and preprocessing to model training and deployment} {original_statement=Ensure best practices in code quality, testing, and documentation are followed within the team., group=[{task=Ensure best practices in code quality are followed within the team}, {task=Ensure best practices in testing are followed within the team}, {task=Ensure best practices in documentation are followed within the team}], group_type=AND} {original_statement=Stay updated with the latest advancements in machine learning and AI technologies, and drive innovation within the team., group=[{task=Stay updated with the latest advancements in machine learning and AI technologies}, {task=Drive innovation within the team}], group_type=AND}",
#         "requiredQualifications": "{original_statement=Bachelor’s or Master’s degree in Computer Science, Engineering, Mathematics, or a related field., group=[{group=[{requirement=Bachelor’s degree in Computer Science, Engineering, Mathematics, or a related field}, {requirement=Master’s degree in Computer Science, Engineering, Mathematics, or a related field}], group_type=OR}], group_type=AND} {original_statement=Minimum of 5 years of experience in machine learning, with at least 2 years in a leadership or tech lead role., group=[{requirement=Minimum of 5 years of experience in machine learning}, {requirement=At least 2 years in a leadership role}, {requirement=At least 2 years in a tech lead role}], group_type=AND} {original_statement=Strong proficiency in Python and experience with machine learning frameworks such as TensorFlow, PyTorch, or Scikit-learn., group=[{requirement=Strong proficiency in Python}, {requirement=Experience with machine learning frameworks such as TensorFlow, PyTorch, or Scikit-learn}], group_type=AND} {original_statement=Proven track record of deploying machine learning models in production environments., requirement=Proven track record of deploying machine learning models in production environments} {original_statement=Excellent problem-solving skills and the ability to work independently and collaboratively in a fast-paced environment., group=[{requirement=Excellent problem-solving skills}, {requirement=The ability to work independently in a fast-paced environment}, {requirement=The ability to work collaboratively in a fast-paced environment}], group_type=AND} {original_statement=Strong communication skills, with the ability to convey complex technical concepts to non-technical stakeholders., requirement=Strong communication skills, with the ability to convey complex technical concepts to non-technical stakeholders}",
#         "preferredSkills": "{original_statement=Experience with cloud platforms such as AWS, Google Cloud, or Azure., group=[{group=[{skill=Experience with cloud platforms such as AWS}, {skill=Experience with cloud platforms such as Google Cloud}, {skill=Experience with cloud platforms such as Azure}], group_type=OR}], group_type=AND} {original_statement=Familiarity with big data technologies like Hadoop, Spark, or Kafka., group=[{group=[{skill=Familiarity with big data technologies like Hadoop}, {skill=Familiarity with big data technologies like Spark}, {skill=Familiarity with big data technologies like Kafka}], group_type=OR}], group_type=AND} {original_statement=Knowledge of deep learning architectures and natural language processing., group=[{skill=Knowledge of deep learning architectures}, {skill=Knowledge of natural language processing}], group_type=AND} {original_statement=Experience with version control systems, such as Git, and CI/CD pipelines., group=[{skill=Experience with version control systems, such as Git}, {skill=Experience with CI/CD pipelines}], group_type=AND} {original_statement=Strong understanding of data structures, algorithms, and software design principles., group=[{skill=Strong understanding of data structures}, {skill=Strong understanding of algorithms}, {skill=Strong understanding of software design principles}], group_type=AND}",
#         "message": "AI and Machine Learning Solutions industry"
#     }
#     jd_payload_2 = {
#         "id": 1030,
#         "jobTitle": "Mid-level SAP Developer",
#         "companyOverview": "At Tech Innovators Inc., we are committed to delivering cutting-edge technology solutions that empower businesses to achieve their goals. Our team is composed of forward-thinking professionals who are passionate about leveraging technology to drive innovation and efficiency. We pride ourselves on fostering a collaborative and inclusive work environment where creativity and expertise are valued and nurtured.",
#         "keyResponsibilities": "{original_statement=Develop, implement, and maintain SAP applications and solutions to meet business requirements., group=[{group=[{task=Develop SAP applications and solutions to meet business requirements}, {task=Implement SAP applications and solutions to meet business requirements}, {task=Maintain SAP applications and solutions to meet business requirements}], group_type=AND}], group_type=AND} {original_statement=Collaborate with cross-functional teams to gather and analyze requirements, translating them into technical specifications., task=Collaborate with cross-functional teams to gather and analyze requirements, translating them into technical specifications} {original_statement=Customize and configure SAP modules, ensuring seamless integration with existing systems., task=Customize and configure SAP modules, ensuring seamless integration with existing systems} {original_statement=Perform unit testing, integration testing, and support user acceptance testing to ensure high-quality deliverables., group=[{group=[{task=Perform unit testing to ensure high-quality deliverables}, {task=Perform integration testing to ensure high-quality deliverables}, {task=Support user acceptance testing to ensure high-quality deliverables}], group_type=AND}], group_type=AND} {original_statement=Troubleshoot and resolve SAP-related issues, providing timely support and solutions., task=Troubleshoot and resolve SAP-related issues, providing timely support and solutions} {original_statement=Participate in code reviews and contribute to the development of best practices and coding standards., group=[{group=[{task=Participate in code reviews}, {task=Contribute to the development of best practices}, {task=Contribute to the development of coding standards}], group_type=AND}], group_type=AND} {original_statement=Document technical specifications, system configurations, and user manuals for future reference., group=[{group=[{task=Document technical specifications for future reference}, {task=Document system configurations for future reference}, {task=Document user manuals for future reference}], group_type=AND}], group_type=AND} {original_statement=Stay updated with the latest SAP technologies and industry trends to propose innovative solutions., task=Stay updated with the latest SAP technologies and industry trends to propose innovative solutions}",
#         "requiredQualifications": "{original_statement=Bachelor’s degree in Computer Science, Information Technology, or a related field., group=[{group=[{requirement=Bachelor’s degree in Computer Science}, {requirement=Bachelor’s degree in Information Technology}, {requirement=Bachelor’s degree in a related field}], group_type=OR}], group_type=AND} {original_statement=3-5 years of experience in SAP development, including ABAP programming and SAP module customization., group=[{group=[{requirement=3-5 years of experience in SAP development}, {requirement=3-5 years of experience in ABAP programming}, {requirement=3-5 years of experience in SAP module customization}], group_type=AND}], group_type=AND} {original_statement=Strong understanding of SAP modules such as SD, MM, FI/CO, or HR., group=[{group=[{requirement=Strong understanding of SAP modules such as SD}, {requirement=Strong understanding of SAP modules such as MM}, {requirement=Strong understanding of SAP modules such as FI/CO}, {requirement=Strong understanding of SAP modules such as HR}], group_type=OR}], group_type=AND} {original_statement=Proficiency in SAP development tools and methodologies., requirement=Proficiency in SAP development tools and methodologies} {original_statement=Excellent problem-solving skills and attention to detail., group=[{group=[{requirement=Excellent problem-solving skills}, {requirement=Excellent attention to detail}], group_type=AND}], group_type=AND} {original_statement=Strong communication and interpersonal skills, with the ability to work effectively in a team environment., group=[{group=[{requirement=Strong communication skills}, {requirement=Strong interpersonal skills}, {requirement=Ability to work effectively in a team environment}], group_type=AND}], group_type=AND}",
#         "preferredSkills": "{original_statement=Experience with SAP S/4HANA or SAP Fiori., group=[{group=[{skill=Experience with SAP S/4HANA}, {skill=Experience with SAP Fiori}], group_type=OR}], group_type=AND} {original_statement=Knowledge of SAP integration technologies such as SAP PI/PO or SAP Cloud Platform Integration., group=[{group=[{skill=Knowledge of SAP integration technologies such as SAP PI/PO}, {skill=Knowledge of SAP integration technologies such as SAP Cloud Platform Integration}], group_type=OR}], group_type=AND} {original_statement=Familiarity with Agile development methodologies., skill=Familiarity with Agile development methodologies} {original_statement=SAP certification in relevant modules or technologies., skill=SAP certification in relevant modules or technologies} {original_statement=Experience with SAP data migration and data management., group=[{group=[{skill=Experience with SAP data migration}, {skill=Experience with SAP data management}], group_type=AND}], group_type=AND}",
#         "message": "banking"
#     }
#
#     cv_payload = 103  # Assuming CV ID 99 exists
#
#     request_payload = {
#         "cv": cv_payload,
#         "jd": [jd_payload_1, jd_payload_2]
#     }
#
#     response = client.post("/match/cv", json=request_payload)
#
#     print(response.json())
#
#     assert response.status_code == 200
#     assert isinstance(response.json(), list)
#     assert len(response.json()) > 0
#     assert "score" in response.json()[0]
#     assert "explanation" in response.json()[0]
#     assert "id" in response.json()[0]

#
#
# def test_delete_cv():
#     # Assuming CV with id=99 exists in the collection
#     response = client.delete("/delete/cv/105")
#     assert response.status_code == 200
#     assert response.json() == "Success"
#
# def test_delete_jd():
#     # Assuming JD with id=101 exists in the collection
#     response = client.delete("/delete/jd/1001")
#     assert response.status_code == 200
#     assert response.json() == "Success"
